server:
  port: 9001

spring:
  application:
    name: cloud-gateway
  cloud:
    client:
      ipAddress:
        localhost

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

zuul:
  ignored-services: "*"
  sensitiveHeaders:
  host:
    connect-time-millis: 5000
    socket-time-millis: 5000

ribbon:
  MaxAutoRetries: 1
  ConnectionTimeout: 1000
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000